# -*- coding: utf-8 -*-
"""week 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XRZ7kJQaRZUUyyYTGDGH6b1Cq5ZNxN2b
"""

double=lambda x:2*x
print(double(10))
add=lambda x,y:x+y
print(add(12,24))

list1=[30,29,42,55,66]
is_even=lambda x:x%2==0
list2=list(filter(is_even, list1))
print(list2)

def addition(n):
  return n+n
numbers=(11,12,13,14)
result=map(addition , numbers)
print(list(result))

#to find sum of numbers for the elements of the listby using reduce()
import functools
def main():
  list=[10,1,24,36,49,0]
  sum=functools.reduce(lambda x,y:x+y,list)
  print(Sum)

