# -*- coding: utf-8 -*-
"""Week - 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qfUyMFhBUmlIWA9FApbJlMd6sNV9WBHC
"""

def add(a,b):
 return a+b
def sub(c,d):
 return c-d
def mul(e,f):
 return e*f
def div(g,h):
 return g/h
print("=================")
print("1. TO PERFORM ADDITITON")
print("2. TO PERFORM SUBTRACTION")
print("3. TO PERFORM MULTIPICATION")
print("4. TO PERFORM DIVISION")
print("=================")
choice = int(input("Enter Your choice"))
if choice ==1:
 a=int(input("Enter the 1st value"))
 b=int(input("Enter the 2nd value"))
 print(add(a,b))
elif choice ==2:
 c=int(input("Enter the 1st value"))
 d=int(input("Enter the 2nd value"))
 print(sub(c,d))
elif choice ==3:
 e=int(input("Enter the 1st value"))
 f=int(input("Enter the 2nd value"))
 print(mul(e,f))
elif choice ==4:
 g=int(input("Enter the 1st value"))
 h=int(input("Enter the 2nd value"))
 print(div(g,h))
else:
 print("wrong choice")

def isPalindrome(s):
  return s
s="malayalam"
if s:
  print("Is a palindrome")
else:
  print("Not a palindrome")

def fact(n):
  if n==1:
    return n
  else:
    return n*fact(n-1)
num =int(input("Enter a no:"))
if num==0:
  print("The factorial of 0 or 1")
else:
  print("The factorial of",num,"is",fact(num))

def fun(list1,list2):
  for x in list1:
    for y in list2:
      if x==y:
        result=True
      else:
        result=False
        return result
      print(fun([1,2,3,4,5],[1,2,3,4,5]))

list='Welcome to python'
print(list.endswith('python'))