# -*- coding: utf-8 -*-
"""Week - 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KME97jsp3w4ouiD6iu-vuC8eOVG1ToFX
"""

a=int(input("Enter a's value:"))
b=int(input("Enter b's value:"))
c=a+b
print("Sum of two numbers=",c)

a=int(input("Enter any number:"))
if(a>0):
  print("The given number is positive")
else:
  print("The given number is negative")

a=int(input("Enter a's value:"))
b=int(input("Enter b's value:"))
c=int(input("Enter c's value:"))
if(a>b and a>c):
  print("a is greater",a)
elif(b>a and b>c):
  print("c is greater",c)

x=int(input("Enter any number between 1 to 7:"))
if(x==1):
  print("Monday")
elif(x==2):
  print("Tuesday")
elif(x==3):
  print("Wednesday")
elif(x==4):
  print("Thursday")
elif(x==5):
  print("Friday")
elif(x==6):
  print("Saturday")
else:
  print("Sunday")